HackathonBundle\Entity\Etablissements:
    type: entity
    table: null
    repositoryClass: HackathonBundle\Repository\EtablissementsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        etoiles:
            type: integer
        latitude:
            type: integer
        longitude:
            type: string
            length: 255


    manyToOne:
        categorie:
           targetEntity: HackathonBundle\Entity\CategoriesEtablissements
           inversedBy: etablissement

    oneToOne:
        poids:
            targetEntity: HackathonBundle\Entity\PoidsEtablissements
            mappedBy: etablissement

    lifecycleCallbacks: {  }
