HackathonBundle\Entity\Vacances:
    type: entity
    table: null
    repositoryClass: HackathonBundle\Repository\VacancesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        lieu:
            type: string
            length: 255
        dateDepart:
            type: datetime
            column: date_depart
        dateRetour:
            type: datetime
            column: date_retour
        budget:
            type: integer

    manyToMany:
        participants:
            targetEntity: HackathonBundle\Entity\User
            inversedBy: vacances
            joinTable:
                name: Vacances_Participants
                joinColumns:
                    vacances_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    user_id:
                        referencedColumnName: id



    lifecycleCallbacks: {  }
