hackathon_homepage:
    path:     /
    defaults: { _controller: HackathonBundle:Default:index }

formulaire_vacances:
    path: /formulaire
    defaults: {_controller: HackathonBundle:Vacances:formulaire }
