<?php

namespace HackathonBundle\Repository;

/**
 * CategoriesEtablissementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesEtablissementsRepository extends \Doctrine\ORM\EntityRepository
{
}
