<?php

namespace HackathonBundle\Repository;

/**
 * EtablissementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementsRepository extends \Doctrine\ORM\EntityRepository
{
}
