<?php

namespace HackathonBundle\Repository;

/**
 * PoidsEtablissementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoidsEtablissementsRepository extends \Doctrine\ORM\EntityRepository
{
}
