<?php

namespace HackathonBundle\Repository;

/**
 * VacancesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VacancesRepository extends \Doctrine\ORM\EntityRepository
{
}
